name: Greetings

on:
  #   push:
  #     branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello World"
