name: Greetings

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
        type: string

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Specify your Node.js version

      - name: Install Dependencies
        run: npm ci # Using npm ci for cleaner installs in CI

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.APP_NAME}}:${{secrets.DOCKER_TAG}}
